Repository mebitek/performer, pull requests merged in 2024-01, with the labels that each got.

#28 simplify note tie UX
  src/apps/sequencer/ui/pages/NoteSequenceEditPage.cpp
Labels: enhancement

#39 [Pattern Follow] Implement Display and LaunchPad tracking on display
  src/apps/sequencer/model/BaseTrackPatternFollow.h
  src/apps/sequencer/model/Types.h
  src/apps/sequencer/ui/pages/CurveSequenceEditPage.cpp
  src/apps/sequencer/ui/pages/CurveSequenceEditPage.h
  src/apps/sequencer/ui/pages/NoteSequenceEditPage.cpp
  src/platform/sim/sim/TargetTrace.cpp
Labels: bug, enhancement

#40 Feature 47
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  src/apps/sequencer/Config.h
  src/apps/sequencer/engine/SequenceState.cpp
  src/apps/sequencer/engine/generators/RandomGenerator.cpp
  src/apps/sequencer/engine/generators/RandomGenerator.h
  src/apps/sequencer/model/BaseTrack.h
  src/apps/sequencer/model/BaseTrackPatternFollow.h
  src/apps/sequencer/model/CurveTrack.h
  src/apps/sequencer/model/MidiCvTrack.h
  src/apps/sequencer/model/NoteSequence.cpp
  src/apps/sequencer/model/NoteSequence.h
  src/apps/sequencer/model/NoteTrack.h
  src/apps/sequencer/model/Project.h
  src/apps/sequencer/model/Scale.h
  src/apps/sequencer/model/Types.h
  src/apps/sequencer/model/UserScale.h
  src/apps/sequencer/model/UserSettings.h
  src/apps/sequencer/ui/controllers/launchpad/LaunchpadController.cpp
  src/apps/sequencer/ui/controllers/launchpad/LaunchpadController.h
  src/apps/sequencer/ui/controllers/launchpad/LaunchpadMk2Device.h
  src/apps/sequencer/ui/controllers/launchpad/LaunchpadMk3Device.h
  src/apps/sequencer/ui/controllers/launchpad/LaunchpadProDevice.h
  src/apps/sequencer/ui/controllers/launchpad/LaunchpadProMk3Device.h
  src/apps/sequencer/ui/model/CurveTrackListModel.h
  src/apps/sequencer/ui/model/NoteSequenceListModel.h
  src/apps/sequencer/ui/model/ProjectListModel.h
  src/apps/sequencer/ui/pages/CurveSequenceEditPage.cpp
  src/apps/sequencer/ui/pages/MidiOutputPage.h
  src/apps/sequencer/ui/pages/NoteSequenceEditPage.cpp
  src/apps/sequencer/ui/pages/NoteSequencePage.cpp
  src/apps/sequencer/ui/pages/OverviewPage.cpp
  src/apps/sequencer/ui/pages/PatternPage.cpp
  src/apps/sequencer/ui/pages/PatternPage.h
  src/apps/sequencer/ui/pages/ProjectPage.cpp
  src/apps/sequencer/ui/pages/RoutingPage.h
  src/apps/sequencer/ui/pages/StartupPage.cpp
  src/apps/sequencer/ui/painters/SequencePainter.cpp
  src/platform/sim/sim/TargetTrace.cpp
Labels: bug, enhancement

#37 Gh pages feature 47
  .gitignore
  _pages/manual/index.md
Labels: documentation

#50 Feature 48 documentation
  .gitignore
  _pages/manual/index.md
Labels: documentation
